//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.28 at 05:35:32 PM CST 
//


package com.accela.adapter.model.function;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.accela.adapter.model.auth.AuthenticateUser;
import com.accela.adapter.model.auth.AuthenticateUserResponse;
import com.accela.adapter.model.cap.GetAdditionalInformationGroups;
import com.accela.adapter.model.cap.GetAdditionalInformationGroupsResponse;
import com.accela.adapter.model.cap.InitiateCAP;
import com.accela.adapter.model.cap.InitiateCAPResponse;
import com.accela.adapter.model.document.CreateDocument;
import com.accela.adapter.model.document.CreateDocumentResponse;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetCAPs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="System">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="XMLVersion" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                             &lt;element name="ServiceProviderCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MaxRows" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="StartRow" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="EndRow" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="TotalRows" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="ApplicationState" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="Context" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LanguageID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="returnElements">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="returnElement" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CAPTypeIds">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CAPTypeId">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Keys">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="StatusDateRange">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CAPStatuses">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CAPStatus">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Keys">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="parentCAPId">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Keys">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="subsidiaryCAPId">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Keys">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="useCachedCAPs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="withOpenInspectionsOnly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"getCAPs",
		"updateCAPResponse", 
		"updateCAP",
		"initiateCAPResponse", 
		"initiateCAP",
		"getInspections",
		"getCAPsResponse", 
		"authenticateUser",
		"authenticateUserResponse",
		"getInspectionsResponse",
		"getAdditionalInformationGroups",
		"getAdditionalInformationGroupsResponse",
		"createDocument",
		"createDocumentResponse"

})
@XmlRootElement(name = "GovXML")
public class GovXML {

    @XmlElement(name = "GetCAPs", required = true)
    protected GetCAPs getCAPs;
    
    @XmlElement(name = "UpdateCAPResponse")
    protected List<UpdateCAPResponse> updateCAPResponse;
    
    @XmlElement(name = "UpdateCAP", required = true)
    protected UpdateCAP updateCAP;

    @XmlElement(name = "InitiateCAPResponse")
    protected List<InitiateCAPResponse> initiateCAPResponse;

    @XmlElement(name = "InitiateCAP", required = true)
    protected InitiateCAP initiateCAP;

    @XmlElement(name = "GetInspections", required = true)
    protected GetInspections getInspections;

	@XmlElement(name = "GetInspectionsResponse", required = true)
    protected GetInspectionsResponse getInspectionsResponse;

    @XmlElement(name = "GetCAPsResponse", required = true)
    protected GetCAPsResponse getCAPsResponse;
    
    @XmlElement(name = "AuthenticateUser")
    protected AuthenticateUser authenticateUser;
    
    @XmlElement(name = "AuthenticateUserResponse")
    protected AuthenticateUserResponse authenticateUserResponse;

    @XmlElement(name = "GetAdditionalInformationGroups")
    protected GetAdditionalInformationGroups getAdditionalInformationGroups;
    
    @XmlElement(name = "GetAdditionalInformationGroupsResponse")
    protected GetAdditionalInformationGroupsResponse getAdditionalInformationGroupsResponse;
    
    @XmlElement(name = "CreateDocument")
    protected CreateDocument createDocument;
    
    @XmlElement(name = "CreateDocumentResponse", required = true)
    protected CreateDocumentResponse createDocumentResponse;


    public GetAdditionalInformationGroupsResponse getGetAdditionalInformationGroupsResponse()
	{
		return getAdditionalInformationGroupsResponse;
	}

	public void setGetAdditionalInformationGroupsResponse(
			GetAdditionalInformationGroupsResponse getAdditionalInformationGroupsResponse)
	{
		this.getAdditionalInformationGroupsResponse = getAdditionalInformationGroupsResponse;
	}

	public void setGetAdditionalInformationGroups(GetAdditionalInformationGroups getAdditionalInformationGroups)
	{
		this.getAdditionalInformationGroups = getAdditionalInformationGroups;
	}

	public void setUpdateCAPResponse(List<UpdateCAPResponse> updateCAPResponse)
	{
		this.updateCAPResponse = updateCAPResponse;
	}

	public void setInitiateCAPResponse(List<InitiateCAPResponse> initiateCAPResponse)
	{
		this.initiateCAPResponse = initiateCAPResponse;
	}

	public void setAuthenticateUserResponse(AuthenticateUserResponse authenticateUserResponse)
	{
		this.authenticateUserResponse = authenticateUserResponse;
	}

	/**
     * Gets the value of the getCAPsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GetCAPsResponse }
     *     
     */
    public GetCAPsResponse getGetCAPsResponse() {
        return getCAPsResponse;
    }

    /**
     * Sets the value of the getCAPsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetCAPsResponse }
     *     
     */
    public void setGetCAPsResponse(GetCAPsResponse value) {
        this.getCAPsResponse = value;
    }
    
    /**
     * Gets the value of the getCAPs property.
     * 
     * @return
     *     possible object is
     *     {@link GetCAPs }
     *     
     */
    public GetCAPs getGetCAPs() {
        return getCAPs;
    }

    /**
     * Sets the value of the getCAPs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetCAPs }
     *     
     */
    public void setGetCAPs(GetCAPs value) {
        this.getCAPs = value;
    }

    /**
     * Gets the value of the updateCAPResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateCAPResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateCAPResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateCAPResponse }
     * 
     * 
     */
    public List<UpdateCAPResponse> getUpdateCAPResponse() {
        if (updateCAPResponse == null) {
            updateCAPResponse = new ArrayList<UpdateCAPResponse>();
        }
        return this.updateCAPResponse;
    }

    /**
     * Gets the value of the updateCAP property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateCAP }
     *     
     */
    public UpdateCAP getUpdateCAP() {
        return updateCAP;
    }

    /**
     * Sets the value of the updateCAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateCAP }
     *     
     */
    public void setUpdateCAP(UpdateCAP value) {
        this.updateCAP = value;
    }
    
    /**
     * Gets the value of the initiateCAPResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initiateCAPResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitiateCAPResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InitiateCAPResponse }
     * 
     * 
     */
    public List<InitiateCAPResponse> getInitiateCAPResponse() {
        if (initiateCAPResponse == null) {
            initiateCAPResponse = new ArrayList<InitiateCAPResponse>();
        }
        return this.initiateCAPResponse;
    }
    
    /**
     * Gets the value of the initiateCAP property.
     * 
     * @return
     *     possible object is
     *     {@link InitiateCAP }
     *     
     */
    public InitiateCAP getInitiateCAP() {
        return initiateCAP;
    }

    /**
     * Sets the value of the initiateCAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiateCAP }
     *     
     */
    public void setInitiateCAP(InitiateCAP value) {
        this.initiateCAP = value;
    }
    
    /**
     * Gets the value of the getInspections property.
     * 
     * @return
     *     possible object is
     *     {@link GetInspections }
     *     
     */
    public GetInspections getGetInspections() {
        return getInspections;
    }

    /**
     * Sets the value of the getInspections property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetInspections }
     *     
     */
    public void setGetInspections(GetInspections value) {
        this.getInspections = value;
    }
    
  
    /**
     * Gets the value of the authenticateUserResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authenticateUserResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthenticateUserResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthenticateUserResponse }
     * 
     * 
     */
    public AuthenticateUserResponse getAuthenticateUserResponse() {       
        return this.authenticateUserResponse;
    }
    
    /**
	 * @return the getInspectionsResponse
	 */
	
	public GetInspectionsResponse getGetInspectionsResponse()
	{
		return getInspectionsResponse;
	}

	/**
	 * @param getInspectionsResponse the getInspectionsResponse to set
	 */
	public void setGetInspectionsResponse(GetInspectionsResponse getInspectionsResponse)
	{
		this.getInspectionsResponse = getInspectionsResponse;
	}

	/**
     * Gets the value of the authenticateUser property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticateUser }
     *     
     */
    public AuthenticateUser getAuthenticateUser() {
        return authenticateUser;
    }

    /**
     * Sets the value of the authenticateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticateUser }
     *     
     */
    public void setAuthenticateUser(AuthenticateUser value) {
        this.authenticateUser = value;
    }

    /**
     * Gets the value of the getAdditionalInformationGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the getAdditionalInformationGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetAdditionalInformationGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetAdditionalInformationGroups }
     * 
     * 
     */
    public GetAdditionalInformationGroups getGetAdditionalInformationGroups() {
      
        return this.getAdditionalInformationGroups;
    }

    /**
     * Gets the value of the createDocument property.
     * 
     * @return
     *     possible object is
     *     {@link CreateDocument }
     *     
     */
    public CreateDocument getCreateDocument() {
        return createDocument;
    }

    /**
     * Sets the value of the createDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateDocument }
     *     
     */
    public void setCreateDocument(CreateDocument value) {
        this.createDocument = value;
    }
    
   

    /**
     * Gets the value of the createDocumentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CreateDocumentResponse }
     *     
     */
    public CreateDocumentResponse getCreateDocumentResponse() {
        return createDocumentResponse;
    }

    /**
     * Sets the value of the createDocumentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateDocumentResponse }
     *     
     */
    public void setCreateDocumentResponse(CreateDocumentResponse value) {
        this.createDocumentResponse = value;
    }
}
