//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 09:49:24 PM CST 
//


package com.accela.cers.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntityKeys" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="Transaction" form="unqualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TransactionKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                   &lt;element name="RegulatorTransactionKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                   &lt;element name="TransactionReceived" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                   &lt;element name="TransactionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                   &lt;element name="DetailUri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Summary" form="unqualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataProcessedOn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                   &lt;element name="ErrorSummary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                   &lt;element name="RequiredSummary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                   &lt;element name="WarningSummary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                   &lt;element name="AdvisorySummary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GuidanceMessages" form="unqualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GuidanceMessage" maxOccurs="unbounded" minOccurs="0" form="unqualified">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="guidanceCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="entityResource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="regulatorKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityKeys",
    "transaction",
    "summary",
    "guidanceMessages"
})
@XmlRootElement(name = "CMESubmittalResponse")
public class CMESubmittalResponse {

    @XmlElement(name = "EntityKeys")
    protected String entityKeys;
    @XmlElement(name = "Transaction", required = true)
    protected CMESubmittalResponse.Transaction transaction;
    @XmlElement(name = "Summary", required = true)
    protected Summary summary;
    @XmlElement(name = "GuidanceMessages", required = true)
    protected GuidanceMessages guidanceMessages;

    /**
     * Gets the value of the entityKeys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityKeys() {
        return entityKeys;
    }

    /**
     * Sets the value of the entityKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityKeys(String value) {
        this.entityKeys = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link CMESubmittalResponse.Transaction }
     *     
     */
    public CMESubmittalResponse.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CMESubmittalResponse.Transaction }
     *     
     */
    public void setTransaction(CMESubmittalResponse.Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link Summary }
     *     
     */
    public Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary }
     *     
     */
    public void setSummary(Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the guidanceMessages property.
     * 
     * @return
     *     possible object is
     *     {@link GuidanceMessages }
     *     
     */
    public GuidanceMessages getGuidanceMessages() {
        return guidanceMessages;
    }

    /**
     * Sets the value of the guidanceMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuidanceMessages }
     *     
     */
    public void setGuidanceMessages(GuidanceMessages value) {
        this.guidanceMessages = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TransactionKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
     *         &lt;element name="RegulatorTransactionKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
     *         &lt;element name="TransactionReceived" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
     *         &lt;element name="TransactionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
     *         &lt;element name="DetailUri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionKey",
        "regulatorTransactionKey",
        "transactionReceived",
        "transactionStatus",
        "detailUri"
    })
    public static class Transaction {

        @XmlElement(name = "TransactionKey")
        protected String transactionKey;
        @XmlElement(name = "RegulatorTransactionKey")
        protected String regulatorTransactionKey;
        @XmlElement(name = "TransactionReceived")
        protected String transactionReceived;
        @XmlElement(name = "TransactionStatus")
        protected String transactionStatus;
        @XmlElement(name = "DetailUri")
        protected String detailUri;

        /**
         * Gets the value of the transactionKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionKey() {
            return transactionKey;
        }

        /**
         * Sets the value of the transactionKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionKey(String value) {
            this.transactionKey = value;
        }

        /**
         * Gets the value of the regulatorTransactionKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegulatorTransactionKey() {
            return regulatorTransactionKey;
        }

        /**
         * Sets the value of the regulatorTransactionKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegulatorTransactionKey(String value) {
            this.regulatorTransactionKey = value;
        }

        /**
         * Gets the value of the transactionReceived property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionReceived() {
            return transactionReceived;
        }

        /**
         * Sets the value of the transactionReceived property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionReceived(String value) {
            this.transactionReceived = value;
        }

        /**
         * Gets the value of the transactionStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionStatus() {
            return transactionStatus;
        }

        /**
         * Sets the value of the transactionStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionStatus(String value) {
            this.transactionStatus = value;
        }

        /**
         * Gets the value of the detailUri property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDetailUri() {
            return detailUri;
        }

        /**
         * Sets the value of the detailUri property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDetailUri(String value) {
            this.detailUri = value;
        }

    }

}
