//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 02:57:54 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.accela.com/schema/AccelaOpenSystemInterfaceXML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.accela.adapter.model.document;
