//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authenticateUserResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authenticateUserResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aboutExpiredDays" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="activeInspector" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="allowChangePassword" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasGISLicense" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="inspectorId" type="{}inspectorId" minOccurs="0"/>
 *         &lt;element name="system" type="{}system" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authenticateUserResponse", propOrder = {
    "aboutExpiredDays",
    "activeInspector",
    "allowChangePassword",
    "hasGISLicense",
    "inspectorId",
    "system"
})
public class AuthenticateUserResponse {

    protected Integer aboutExpiredDays;
    protected Boolean activeInspector;
    protected Boolean allowChangePassword;
    protected Boolean hasGISLicense;
    protected InspectorId inspectorId;
    protected System system;

    /**
     * Gets the value of the aboutExpiredDays property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAboutExpiredDays() {
        return aboutExpiredDays;
    }

    /**
     * Sets the value of the aboutExpiredDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAboutExpiredDays(Integer value) {
        this.aboutExpiredDays = value;
    }

    /**
     * Gets the value of the activeInspector property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActiveInspector() {
        return activeInspector;
    }

    /**
     * Sets the value of the activeInspector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActiveInspector(Boolean value) {
        this.activeInspector = value;
    }

    /**
     * Gets the value of the allowChangePassword property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowChangePassword() {
        return allowChangePassword;
    }

    /**
     * Sets the value of the allowChangePassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowChangePassword(Boolean value) {
        this.allowChangePassword = value;
    }

    /**
     * Gets the value of the hasGISLicense property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasGISLicense() {
        return hasGISLicense;
    }

    /**
     * Sets the value of the hasGISLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasGISLicense(Boolean value) {
        this.hasGISLicense = value;
    }

    /**
     * Gets the value of the inspectorId property.
     * 
     * @return
     *     possible object is
     *     {@link InspectorId }
     *     
     */
    public InspectorId getInspectorId() {
        return inspectorId;
    }

    /**
     * Sets the value of the inspectorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectorId }
     *     
     */
    public void setInspectorId(InspectorId value) {
        this.inspectorId = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

}
