//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for calculateRouteResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="calculateRouteResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="routeNodeIds" type="{}routeNodeIds" minOccurs="0"/>
 *         &lt;element name="routeNodes" type="{}routeNodes" minOccurs="0"/>
 *         &lt;element name="routeSegments" type="{}routeSegments" minOccurs="0"/>
 *         &lt;element name="system" type="{}system" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calculateRouteResponse", propOrder = {
    "routeNodeIds",
    "routeNodes",
    "routeSegments",
    "system"
})
public class CalculateRouteResponse {

    protected RouteNodeIds routeNodeIds;
    protected RouteNodes routeNodes;
    protected RouteSegments routeSegments;
    protected System system;

    /**
     * Gets the value of the routeNodeIds property.
     * 
     * @return
     *     possible object is
     *     {@link RouteNodeIds }
     *     
     */
    public RouteNodeIds getRouteNodeIds() {
        return routeNodeIds;
    }

    /**
     * Sets the value of the routeNodeIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteNodeIds }
     *     
     */
    public void setRouteNodeIds(RouteNodeIds value) {
        this.routeNodeIds = value;
    }

    /**
     * Gets the value of the routeNodes property.
     * 
     * @return
     *     possible object is
     *     {@link RouteNodes }
     *     
     */
    public RouteNodes getRouteNodes() {
        return routeNodes;
    }

    /**
     * Sets the value of the routeNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteNodes }
     *     
     */
    public void setRouteNodes(RouteNodes value) {
        this.routeNodes = value;
    }

    /**
     * Gets the value of the routeSegments property.
     * 
     * @return
     *     possible object is
     *     {@link RouteSegments }
     *     
     */
    public RouteSegments getRouteSegments() {
        return routeSegments;
    }

    /**
     * Sets the value of the routeSegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteSegments }
     *     
     */
    public void setRouteSegments(RouteSegments value) {
        this.routeSegments = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

}
