//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for calculateRoute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="calculateRoute">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="calculationMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="calculationPriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mapServiceId" type="{}mapServiceId" minOccurs="0"/>
 *         &lt;element name="reorderRoute" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="returnRouteSegments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="returnRouteToFirstNode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="routeNodes" type="{}routeNodes" minOccurs="0"/>
 *         &lt;element name="system" type="{}system" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calculateRoute", propOrder = {
    "calculationMethod",
    "calculationPriority",
    "mapServiceId",
    "reorderRoute",
    "returnRouteSegments",
    "returnRouteToFirstNode",
    "routeNodes",
    "system"
})
public class CalculateRoute {

    protected String calculationMethod;
    protected String calculationPriority;
    protected MapServiceId mapServiceId;
    protected Boolean reorderRoute;
    protected Boolean returnRouteSegments;
    protected Boolean returnRouteToFirstNode;
    protected RouteNodes routeNodes;
    protected System system;

    /**
     * Gets the value of the calculationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculationMethod() {
        return calculationMethod;
    }

    /**
     * Sets the value of the calculationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculationMethod(String value) {
        this.calculationMethod = value;
    }

    /**
     * Gets the value of the calculationPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculationPriority() {
        return calculationPriority;
    }

    /**
     * Sets the value of the calculationPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculationPriority(String value) {
        this.calculationPriority = value;
    }

    /**
     * Gets the value of the mapServiceId property.
     * 
     * @return
     *     possible object is
     *     {@link MapServiceId }
     *     
     */
    public MapServiceId getMapServiceId() {
        return mapServiceId;
    }

    /**
     * Sets the value of the mapServiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapServiceId }
     *     
     */
    public void setMapServiceId(MapServiceId value) {
        this.mapServiceId = value;
    }

    /**
     * Gets the value of the reorderRoute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReorderRoute() {
        return reorderRoute;
    }

    /**
     * Sets the value of the reorderRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReorderRoute(Boolean value) {
        this.reorderRoute = value;
    }

    /**
     * Gets the value of the returnRouteSegments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnRouteSegments() {
        return returnRouteSegments;
    }

    /**
     * Sets the value of the returnRouteSegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnRouteSegments(Boolean value) {
        this.returnRouteSegments = value;
    }

    /**
     * Gets the value of the returnRouteToFirstNode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnRouteToFirstNode() {
        return returnRouteToFirstNode;
    }

    /**
     * Sets the value of the returnRouteToFirstNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnRouteToFirstNode(Boolean value) {
        this.returnRouteToFirstNode = value;
    }

    /**
     * Gets the value of the routeNodes property.
     * 
     * @return
     *     possible object is
     *     {@link RouteNodes }
     *     
     */
    public RouteNodes getRouteNodes() {
        return routeNodes;
    }

    /**
     * Sets the value of the routeNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteNodes }
     *     
     */
    public void setRouteNodes(RouteNodes value) {
        this.routeNodes = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

}
