//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for capInspections complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="capInspections">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capInspection" type="{}mapItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nextInspSchedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nextInspection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "capInspections", propOrder = {
    "capInspection",
    "nextInspSchedDate",
    "nextInspection"
})
public class CapInspections {

    @XmlElement(nillable = true)
    protected List<MapItem> capInspection;
    protected String nextInspSchedDate;
    protected String nextInspection;

    /**
     * Gets the value of the capInspection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capInspection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapInspection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MapItem }
     * 
     * 
     */
    public List<MapItem> getCapInspection() {
        if (capInspection == null) {
            capInspection = new ArrayList<MapItem>();
        }
        return this.capInspection;
    }

    /**
     * Gets the value of the nextInspSchedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextInspSchedDate() {
        return nextInspSchedDate;
    }

    /**
     * Sets the value of the nextInspSchedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextInspSchedDate(String value) {
        this.nextInspSchedDate = value;
    }

    /**
     * Gets the value of the nextInspection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextInspection() {
        return nextInspection;
    }

    /**
     * Sets the value of the nextInspection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextInspection(String value) {
        this.nextInspection = value;
    }

}
