//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for detail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="detail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addresses" type="{}addresses" minOccurs="0"/>
 *         &lt;element name="capConditions" type="{}capConditions" minOccurs="0"/>
 *         &lt;element name="capContacts" type="{}capContacts" minOccurs="0"/>
 *         &lt;element name="capFees" type="{}capFees" minOccurs="0"/>
 *         &lt;element name="capInspections" type="{}capInspections" minOccurs="0"/>
 *         &lt;element name="capProjectInfo" type="{}capProjectInformations" minOccurs="0"/>
 *         &lt;element name="capWorkflows" type="{}capWorkflows" minOccurs="0"/>
 *         &lt;element name="identifyDisplay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{}type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detail", propOrder = {
    "addresses",
    "capConditions",
    "capContacts",
    "capFees",
    "capInspections",
    "capProjectInfo",
    "capWorkflows",
    "identifyDisplay",
    "type"
})
public class Detail {

    protected Addresses addresses;
    protected CapConditions capConditions;
    protected CapContacts capContacts;
    protected CapFees capFees;
    protected CapInspections capInspections;
    protected CapProjectInformations capProjectInfo;
    protected CapWorkflows capWorkflows;
    protected String identifyDisplay;
    protected Type type;

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link Addresses }
     *     
     */
    public Addresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addresses }
     *     
     */
    public void setAddresses(Addresses value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the capConditions property.
     * 
     * @return
     *     possible object is
     *     {@link CapConditions }
     *     
     */
    public CapConditions getCapConditions() {
        return capConditions;
    }

    /**
     * Sets the value of the capConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapConditions }
     *     
     */
    public void setCapConditions(CapConditions value) {
        this.capConditions = value;
    }

    /**
     * Gets the value of the capContacts property.
     * 
     * @return
     *     possible object is
     *     {@link CapContacts }
     *     
     */
    public CapContacts getCapContacts() {
        return capContacts;
    }

    /**
     * Sets the value of the capContacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapContacts }
     *     
     */
    public void setCapContacts(CapContacts value) {
        this.capContacts = value;
    }

    /**
     * Gets the value of the capFees property.
     * 
     * @return
     *     possible object is
     *     {@link CapFees }
     *     
     */
    public CapFees getCapFees() {
        return capFees;
    }

    /**
     * Sets the value of the capFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapFees }
     *     
     */
    public void setCapFees(CapFees value) {
        this.capFees = value;
    }

    /**
     * Gets the value of the capInspections property.
     * 
     * @return
     *     possible object is
     *     {@link CapInspections }
     *     
     */
    public CapInspections getCapInspections() {
        return capInspections;
    }

    /**
     * Sets the value of the capInspections property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapInspections }
     *     
     */
    public void setCapInspections(CapInspections value) {
        this.capInspections = value;
    }

    /**
     * Gets the value of the capProjectInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CapProjectInformations }
     *     
     */
    public CapProjectInformations getCapProjectInfo() {
        return capProjectInfo;
    }

    /**
     * Sets the value of the capProjectInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapProjectInformations }
     *     
     */
    public void setCapProjectInfo(CapProjectInformations value) {
        this.capProjectInfo = value;
    }

    /**
     * Gets the value of the capWorkflows property.
     * 
     * @return
     *     possible object is
     *     {@link CapWorkflows }
     *     
     */
    public CapWorkflows getCapWorkflows() {
        return capWorkflows;
    }

    /**
     * Sets the value of the capWorkflows property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapWorkflows }
     *     
     */
    public void setCapWorkflows(CapWorkflows value) {
        this.capWorkflows = value;
    }

    /**
     * Gets the value of the identifyDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifyDisplay() {
        return identifyDisplay;
    }

    /**
     * Sets the value of the identifyDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifyDisplay(String value) {
        this.identifyDisplay = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setType(Type value) {
        this.type = value;
    }

}
