//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getCAPs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getCAPs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activePermitsFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="addressTemplateFields" type="{}templateFields" minOccurs="0"/>
 *         &lt;element name="assetIds" type="{}assetIds" minOccurs="0"/>
 *         &lt;element name="CAPId" type="{}capId" minOccurs="0"/>
 *         &lt;element name="CAPIds" type="{}capIds" minOccurs="0"/>
 *         &lt;element name="CAPStatuses" type="{}capStatuses" minOccurs="0"/>
 *         &lt;element name="CAPTypeId" type="{}capTypeId" minOccurs="0"/>
 *         &lt;element name="CAPTypeIds" type="{}capTypeIds" minOccurs="0"/>
 *         &lt;element name="cap" type="{}cap" minOccurs="0"/>
 *         &lt;element name="compactAddressId" type="{}compactAddressId" minOccurs="0"/>
 *         &lt;element name="contact" type="{}contact" minOccurs="0"/>
 *         &lt;element name="contacts" type="{}contacts" minOccurs="0"/>
 *         &lt;element name="dateRange" type="{}dateRange" minOccurs="0"/>
 *         &lt;element name="dateRanges" type="{}dateRanges" minOccurs="0"/>
 *         &lt;element name="departments" type="{}departments" minOccurs="0"/>
 *         &lt;element name="detailAddress" type="{}detailAddress" minOccurs="0"/>
 *         &lt;element name="GISObjects" type="{}gisObjects" minOccurs="0"/>
 *         &lt;element name="inspectionDepartments" type="{}departments" minOccurs="0"/>
 *         &lt;element name="inspectionDistricts" type="{}inspectionDistricts" minOccurs="0"/>
 *         &lt;element name="inspectionTypes" type="{}inspectionTypes" minOccurs="0"/>
 *         &lt;element name="inspectors" type="{}inspectors" minOccurs="0"/>
 *         &lt;element name="keyword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="license" type="{}license" minOccurs="0"/>
 *         &lt;element name="licenses" type="{}licenses" minOccurs="0"/>
 *         &lt;element name="maxRecordsPerAssetId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="openDate" type="{}dateRange" minOccurs="0"/>
 *         &lt;element name="parcelId" type="{}parcelId" minOccurs="0"/>
 *         &lt;element name="parcelIds" type="{}parcelIds" minOccurs="0"/>
 *         &lt;element name="parcelTemplateFields" type="{}templateFields" minOccurs="0"/>
 *         &lt;element name="parentCAPId" type="{}capId" minOccurs="0"/>
 *         &lt;element name="parentCAPIds" type="{}capIds" minOccurs="0"/>
 *         &lt;element name="partialCAPId" type="{}capId" minOccurs="0"/>
 *         &lt;element name="returnElements" type="{}returnElements" minOccurs="0"/>
 *         &lt;element name="scheduleDate" type="{}dateRanges" minOccurs="0"/>
 *         &lt;element name="spatialDescriptors" type="{}spatialDescriptors" minOccurs="0"/>
 *         &lt;element name="subsidiaryCAPId" type="{}capId" minOccurs="0"/>
 *         &lt;element name="system" type="{}system" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="useCachedCAPs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="withOpenInspectionsOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCAPs", propOrder = {
    "activePermitsFlag",
    "addressTemplateFields",
    "assetIds",
    "capId",
    "capIds",
    "capStatuses",
    "capTypeId",
    "capTypeIds",
    "cap",
    "compactAddressId",
    "contact",
    "contacts",
    "dateRange",
    "dateRanges",
    "departments",
    "detailAddress",
    "gisObjects",
    "inspectionDepartments",
    "inspectionDistricts",
    "inspectionTypes",
    "inspectors",
    "keyword",
    "license",
    "licenses",
    "maxRecordsPerAssetId",
    "openDate",
    "parcelId",
    "parcelIds",
    "parcelTemplateFields",
    "parentCAPId",
    "parentCAPIds",
    "partialCAPId",
    "returnElements",
    "scheduleDate",
    "spatialDescriptors",
    "subsidiaryCAPId",
    "system",
    "type",
    "useCachedCAPs",
    "withOpenInspectionsOnly"
})
public class GetCAPs {

    protected Boolean activePermitsFlag;
    protected TemplateFields addressTemplateFields;
    protected AssetIds assetIds;
    @XmlElement(name = "CAPId")
    protected CapId capId;
    @XmlElement(name = "CAPIds")
    protected CapIds capIds;
    @XmlElement(name = "CAPStatuses")
    protected CapStatuses capStatuses;
    @XmlElement(name = "CAPTypeId")
    protected CapTypeId capTypeId;
    @XmlElement(name = "CAPTypeIds")
    protected CapTypeIds capTypeIds;
    protected Cap cap;
    protected CompactAddressId compactAddressId;
    protected Contact contact;
    protected Contacts contacts;
    protected DateRange dateRange;
    protected DateRanges dateRanges;
    protected Departments departments;
    protected DetailAddress detailAddress;
    @XmlElement(name = "GISObjects")
    protected GisObjects gisObjects;
    protected Departments inspectionDepartments;
    protected InspectionDistricts inspectionDistricts;
    protected InspectionTypes inspectionTypes;
    protected Inspectors inspectors;
    protected String keyword;
    protected License license;
    protected Licenses licenses;
    protected String maxRecordsPerAssetId;
    protected DateRange openDate;
    protected ParcelId parcelId;
    protected ParcelIds parcelIds;
    protected TemplateFields parcelTemplateFields;
    protected CapId parentCAPId;
    protected CapIds parentCAPIds;
    protected CapId partialCAPId;
    protected ReturnElements returnElements;
    protected DateRanges scheduleDate;
    protected SpatialDescriptors spatialDescriptors;
    protected CapId subsidiaryCAPId;
    protected System system;
    protected String type;
    protected Boolean useCachedCAPs;
    protected Boolean withOpenInspectionsOnly;

    /**
     * Gets the value of the activePermitsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActivePermitsFlag() {
        return activePermitsFlag;
    }

    /**
     * Sets the value of the activePermitsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActivePermitsFlag(Boolean value) {
        this.activePermitsFlag = value;
    }

    /**
     * Gets the value of the addressTemplateFields property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateFields }
     *     
     */
    public TemplateFields getAddressTemplateFields() {
        return addressTemplateFields;
    }

    /**
     * Sets the value of the addressTemplateFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateFields }
     *     
     */
    public void setAddressTemplateFields(TemplateFields value) {
        this.addressTemplateFields = value;
    }

    /**
     * Gets the value of the assetIds property.
     * 
     * @return
     *     possible object is
     *     {@link AssetIds }
     *     
     */
    public AssetIds getAssetIds() {
        return assetIds;
    }

    /**
     * Sets the value of the assetIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetIds }
     *     
     */
    public void setAssetIds(AssetIds value) {
        this.assetIds = value;
    }

    /**
     * Gets the value of the capId property.
     * 
     * @return
     *     possible object is
     *     {@link CapId }
     *     
     */
    public CapId getCAPId() {
        return capId;
    }

    /**
     * Sets the value of the capId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapId }
     *     
     */
    public void setCAPId(CapId value) {
        this.capId = value;
    }

    /**
     * Gets the value of the capIds property.
     * 
     * @return
     *     possible object is
     *     {@link CapIds }
     *     
     */
    public CapIds getCAPIds() {
        return capIds;
    }

    /**
     * Sets the value of the capIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapIds }
     *     
     */
    public void setCAPIds(CapIds value) {
        this.capIds = value;
    }

    /**
     * Gets the value of the capStatuses property.
     * 
     * @return
     *     possible object is
     *     {@link CapStatuses }
     *     
     */
    public CapStatuses getCAPStatuses() {
        return capStatuses;
    }

    /**
     * Sets the value of the capStatuses property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapStatuses }
     *     
     */
    public void setCAPStatuses(CapStatuses value) {
        this.capStatuses = value;
    }

    /**
     * Gets the value of the capTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link CapTypeId }
     *     
     */
    public CapTypeId getCAPTypeId() {
        return capTypeId;
    }

    /**
     * Sets the value of the capTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapTypeId }
     *     
     */
    public void setCAPTypeId(CapTypeId value) {
        this.capTypeId = value;
    }

    /**
     * Gets the value of the capTypeIds property.
     * 
     * @return
     *     possible object is
     *     {@link CapTypeIds }
     *     
     */
    public CapTypeIds getCAPTypeIds() {
        return capTypeIds;
    }

    /**
     * Sets the value of the capTypeIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapTypeIds }
     *     
     */
    public void setCAPTypeIds(CapTypeIds value) {
        this.capTypeIds = value;
    }

    /**
     * Gets the value of the cap property.
     * 
     * @return
     *     possible object is
     *     {@link Cap }
     *     
     */
    public Cap getCap() {
        return cap;
    }

    /**
     * Sets the value of the cap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cap }
     *     
     */
    public void setCap(Cap value) {
        this.cap = value;
    }

    /**
     * Gets the value of the compactAddressId property.
     * 
     * @return
     *     possible object is
     *     {@link CompactAddressId }
     *     
     */
    public CompactAddressId getCompactAddressId() {
        return compactAddressId;
    }

    /**
     * Sets the value of the compactAddressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompactAddressId }
     *     
     */
    public void setCompactAddressId(CompactAddressId value) {
        this.compactAddressId = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link Contact }
     *     
     */
    public Contact getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contact }
     *     
     */
    public void setContact(Contact value) {
        this.contact = value;
    }

    /**
     * Gets the value of the contacts property.
     * 
     * @return
     *     possible object is
     *     {@link Contacts }
     *     
     */
    public Contacts getContacts() {
        return contacts;
    }

    /**
     * Sets the value of the contacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contacts }
     *     
     */
    public void setContacts(Contacts value) {
        this.contacts = value;
    }

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRange }
     *     
     */
    public DateRange getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRange }
     *     
     */
    public void setDateRange(DateRange value) {
        this.dateRange = value;
    }

    /**
     * Gets the value of the dateRanges property.
     * 
     * @return
     *     possible object is
     *     {@link DateRanges }
     *     
     */
    public DateRanges getDateRanges() {
        return dateRanges;
    }

    /**
     * Sets the value of the dateRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRanges }
     *     
     */
    public void setDateRanges(DateRanges value) {
        this.dateRanges = value;
    }

    /**
     * Gets the value of the departments property.
     * 
     * @return
     *     possible object is
     *     {@link Departments }
     *     
     */
    public Departments getDepartments() {
        return departments;
    }

    /**
     * Sets the value of the departments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Departments }
     *     
     */
    public void setDepartments(Departments value) {
        this.departments = value;
    }

    /**
     * Gets the value of the detailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link DetailAddress }
     *     
     */
    public DetailAddress getDetailAddress() {
        return detailAddress;
    }

    /**
     * Sets the value of the detailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailAddress }
     *     
     */
    public void setDetailAddress(DetailAddress value) {
        this.detailAddress = value;
    }

    /**
     * Gets the value of the gisObjects property.
     * 
     * @return
     *     possible object is
     *     {@link GisObjects }
     *     
     */
    public GisObjects getGISObjects() {
        return gisObjects;
    }

    /**
     * Sets the value of the gisObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link GisObjects }
     *     
     */
    public void setGISObjects(GisObjects value) {
        this.gisObjects = value;
    }

    /**
     * Gets the value of the inspectionDepartments property.
     * 
     * @return
     *     possible object is
     *     {@link Departments }
     *     
     */
    public Departments getInspectionDepartments() {
        return inspectionDepartments;
    }

    /**
     * Sets the value of the inspectionDepartments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Departments }
     *     
     */
    public void setInspectionDepartments(Departments value) {
        this.inspectionDepartments = value;
    }

    /**
     * Gets the value of the inspectionDistricts property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionDistricts }
     *     
     */
    public InspectionDistricts getInspectionDistricts() {
        return inspectionDistricts;
    }

    /**
     * Sets the value of the inspectionDistricts property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionDistricts }
     *     
     */
    public void setInspectionDistricts(InspectionDistricts value) {
        this.inspectionDistricts = value;
    }

    /**
     * Gets the value of the inspectionTypes property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionTypes }
     *     
     */
    public InspectionTypes getInspectionTypes() {
        return inspectionTypes;
    }

    /**
     * Sets the value of the inspectionTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionTypes }
     *     
     */
    public void setInspectionTypes(InspectionTypes value) {
        this.inspectionTypes = value;
    }

    /**
     * Gets the value of the inspectors property.
     * 
     * @return
     *     possible object is
     *     {@link Inspectors }
     *     
     */
    public Inspectors getInspectors() {
        return inspectors;
    }

    /**
     * Sets the value of the inspectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inspectors }
     *     
     */
    public void setInspectors(Inspectors value) {
        this.inspectors = value;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * Sets the value of the keyword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyword(String value) {
        this.keyword = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link License }
     *     
     */
    public License getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link License }
     *     
     */
    public void setLicense(License value) {
        this.license = value;
    }

    /**
     * Gets the value of the licenses property.
     * 
     * @return
     *     possible object is
     *     {@link Licenses }
     *     
     */
    public Licenses getLicenses() {
        return licenses;
    }

    /**
     * Sets the value of the licenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Licenses }
     *     
     */
    public void setLicenses(Licenses value) {
        this.licenses = value;
    }

    /**
     * Gets the value of the maxRecordsPerAssetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxRecordsPerAssetId() {
        return maxRecordsPerAssetId;
    }

    /**
     * Sets the value of the maxRecordsPerAssetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxRecordsPerAssetId(String value) {
        this.maxRecordsPerAssetId = value;
    }

    /**
     * Gets the value of the openDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateRange }
     *     
     */
    public DateRange getOpenDate() {
        return openDate;
    }

    /**
     * Sets the value of the openDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRange }
     *     
     */
    public void setOpenDate(DateRange value) {
        this.openDate = value;
    }

    /**
     * Gets the value of the parcelId property.
     * 
     * @return
     *     possible object is
     *     {@link ParcelId }
     *     
     */
    public ParcelId getParcelId() {
        return parcelId;
    }

    /**
     * Sets the value of the parcelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParcelId }
     *     
     */
    public void setParcelId(ParcelId value) {
        this.parcelId = value;
    }

    /**
     * Gets the value of the parcelIds property.
     * 
     * @return
     *     possible object is
     *     {@link ParcelIds }
     *     
     */
    public ParcelIds getParcelIds() {
        return parcelIds;
    }

    /**
     * Sets the value of the parcelIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParcelIds }
     *     
     */
    public void setParcelIds(ParcelIds value) {
        this.parcelIds = value;
    }

    /**
     * Gets the value of the parcelTemplateFields property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateFields }
     *     
     */
    public TemplateFields getParcelTemplateFields() {
        return parcelTemplateFields;
    }

    /**
     * Sets the value of the parcelTemplateFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateFields }
     *     
     */
    public void setParcelTemplateFields(TemplateFields value) {
        this.parcelTemplateFields = value;
    }

    /**
     * Gets the value of the parentCAPId property.
     * 
     * @return
     *     possible object is
     *     {@link CapId }
     *     
     */
    public CapId getParentCAPId() {
        return parentCAPId;
    }

    /**
     * Sets the value of the parentCAPId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapId }
     *     
     */
    public void setParentCAPId(CapId value) {
        this.parentCAPId = value;
    }

    /**
     * Gets the value of the parentCAPIds property.
     * 
     * @return
     *     possible object is
     *     {@link CapIds }
     *     
     */
    public CapIds getParentCAPIds() {
        return parentCAPIds;
    }

    /**
     * Sets the value of the parentCAPIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapIds }
     *     
     */
    public void setParentCAPIds(CapIds value) {
        this.parentCAPIds = value;
    }

    /**
     * Gets the value of the partialCAPId property.
     * 
     * @return
     *     possible object is
     *     {@link CapId }
     *     
     */
    public CapId getPartialCAPId() {
        return partialCAPId;
    }

    /**
     * Sets the value of the partialCAPId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapId }
     *     
     */
    public void setPartialCAPId(CapId value) {
        this.partialCAPId = value;
    }

    /**
     * Gets the value of the returnElements property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnElements }
     *     
     */
    public ReturnElements getReturnElements() {
        return returnElements;
    }

    /**
     * Sets the value of the returnElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnElements }
     *     
     */
    public void setReturnElements(ReturnElements value) {
        this.returnElements = value;
    }

    /**
     * Gets the value of the scheduleDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateRanges }
     *     
     */
    public DateRanges getScheduleDate() {
        return scheduleDate;
    }

    /**
     * Sets the value of the scheduleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRanges }
     *     
     */
    public void setScheduleDate(DateRanges value) {
        this.scheduleDate = value;
    }

    /**
     * Gets the value of the spatialDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link SpatialDescriptors }
     *     
     */
    public SpatialDescriptors getSpatialDescriptors() {
        return spatialDescriptors;
    }

    /**
     * Sets the value of the spatialDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialDescriptors }
     *     
     */
    public void setSpatialDescriptors(SpatialDescriptors value) {
        this.spatialDescriptors = value;
    }

    /**
     * Gets the value of the subsidiaryCAPId property.
     * 
     * @return
     *     possible object is
     *     {@link CapId }
     *     
     */
    public CapId getSubsidiaryCAPId() {
        return subsidiaryCAPId;
    }

    /**
     * Sets the value of the subsidiaryCAPId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapId }
     *     
     */
    public void setSubsidiaryCAPId(CapId value) {
        this.subsidiaryCAPId = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the useCachedCAPs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseCachedCAPs() {
        return useCachedCAPs;
    }

    /**
     * Sets the value of the useCachedCAPs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseCachedCAPs(Boolean value) {
        this.useCachedCAPs = value;
    }

    /**
     * Gets the value of the withOpenInspectionsOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWithOpenInspectionsOnly() {
        return withOpenInspectionsOnly;
    }

    /**
     * Sets the value of the withOpenInspectionsOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWithOpenInspectionsOnly(Boolean value) {
        this.withOpenInspectionsOnly = value;
    }

}
