//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getDocumentList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getDocumentList">
 *   &lt;complexContent>
 *     &lt;extension base="{}operationRequest">
 *       &lt;sequence>
 *         &lt;element name="edmsAdapters" type="{}edmsAdapters" minOccurs="0"/>
 *         &lt;element name="includeContent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="objectId" type="{}objectId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDocumentList", propOrder = {
    "edmsAdapters",
    "includeContent",
    "objectId"
})
public class GetDocumentList
    extends OperationRequest
{

    protected EdmsAdapters edmsAdapters;
    protected Boolean includeContent;
    protected ObjectId objectId;

    /**
     * Gets the value of the edmsAdapters property.
     * 
     * @return
     *     possible object is
     *     {@link EdmsAdapters }
     *     
     */
    public EdmsAdapters getEdmsAdapters() {
        return edmsAdapters;
    }

    /**
     * Sets the value of the edmsAdapters property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdmsAdapters }
     *     
     */
    public void setEdmsAdapters(EdmsAdapters value) {
        this.edmsAdapters = value;
    }

    /**
     * Gets the value of the includeContent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeContent() {
        return includeContent;
    }

    /**
     * Sets the value of the includeContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeContent(Boolean value) {
        this.includeContent = value;
    }

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectId }
     *     
     */
    public ObjectId getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectId }
     *     
     */
    public void setObjectId(ObjectId value) {
        this.objectId = value;
    }

}
