//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getGuidesheets complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getGuidesheets">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CAPId" type="{}capId" minOccurs="0"/>
 *         &lt;element name="CAPTypeId" type="{}capTypeId" minOccurs="0"/>
 *         &lt;element name="inspectionId" type="{}inspectionId" minOccurs="0"/>
 *         &lt;element name="inspectionType" type="{}inspectionType" minOccurs="0"/>
 *         &lt;element name="system" type="{}system" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getGuidesheets", propOrder = {
    "capId",
    "capTypeId",
    "inspectionId",
    "inspectionType",
    "system"
})
public class GetGuidesheets {

    @XmlElement(name = "CAPId")
    protected CapId capId;
    @XmlElement(name = "CAPTypeId")
    protected CapTypeId capTypeId;
    protected InspectionId inspectionId;
    protected InspectionType inspectionType;
    protected System system;

    /**
     * Gets the value of the capId property.
     * 
     * @return
     *     possible object is
     *     {@link CapId }
     *     
     */
    public CapId getCAPId() {
        return capId;
    }

    /**
     * Sets the value of the capId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapId }
     *     
     */
    public void setCAPId(CapId value) {
        this.capId = value;
    }

    /**
     * Gets the value of the capTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link CapTypeId }
     *     
     */
    public CapTypeId getCAPTypeId() {
        return capTypeId;
    }

    /**
     * Sets the value of the capTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapTypeId }
     *     
     */
    public void setCAPTypeId(CapTypeId value) {
        this.capTypeId = value;
    }

    /**
     * Gets the value of the inspectionId property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionId }
     *     
     */
    public InspectionId getInspectionId() {
        return inspectionId;
    }

    /**
     * Sets the value of the inspectionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionId }
     *     
     */
    public void setInspectionId(InspectionId value) {
        this.inspectionId = value;
    }

    /**
     * Gets the value of the inspectionType property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionType }
     *     
     */
    public InspectionType getInspectionType() {
        return inspectionType;
    }

    /**
     * Sets the value of the inspectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionType }
     *     
     */
    public void setInspectionType(InspectionType value) {
        this.inspectionType = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

}
