//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getGISObjectsByBufferRadius complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getGISObjectsByBufferRadius">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bufferLayer" type="{}bufferLayer" minOccurs="0"/>
 *         &lt;element name="bufferObjects" type="{}bufferObjects" minOccurs="0"/>
 *         &lt;element name="mapServiceId" type="{}mapServiceId" minOccurs="0"/>
 *         &lt;element name="radius" type="{}radius" minOccurs="0"/>
 *         &lt;element name="system" type="{}system" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getGISObjectsByBufferRadius", propOrder = {
    "bufferLayer",
    "bufferObjects",
    "mapServiceId",
    "radius",
    "system"
})
public class GetGISObjectsByBufferRadius {

    protected BufferLayer bufferLayer;
    protected BufferObjects bufferObjects;
    protected MapServiceId mapServiceId;
    protected Radius radius;
    protected System system;

    /**
     * Gets the value of the bufferLayer property.
     * 
     * @return
     *     possible object is
     *     {@link BufferLayer }
     *     
     */
    public BufferLayer getBufferLayer() {
        return bufferLayer;
    }

    /**
     * Sets the value of the bufferLayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BufferLayer }
     *     
     */
    public void setBufferLayer(BufferLayer value) {
        this.bufferLayer = value;
    }

    /**
     * Gets the value of the bufferObjects property.
     * 
     * @return
     *     possible object is
     *     {@link BufferObjects }
     *     
     */
    public BufferObjects getBufferObjects() {
        return bufferObjects;
    }

    /**
     * Sets the value of the bufferObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link BufferObjects }
     *     
     */
    public void setBufferObjects(BufferObjects value) {
        this.bufferObjects = value;
    }

    /**
     * Gets the value of the mapServiceId property.
     * 
     * @return
     *     possible object is
     *     {@link MapServiceId }
     *     
     */
    public MapServiceId getMapServiceId() {
        return mapServiceId;
    }

    /**
     * Sets the value of the mapServiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapServiceId }
     *     
     */
    public void setMapServiceId(MapServiceId value) {
        this.mapServiceId = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link Radius }
     *     
     */
    public Radius getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Radius }
     *     
     */
    public void setRadius(Radius value) {
        this.radius = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

}
