//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getGuideSheetHistories complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getGuideSheetHistories">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capID" type="{}capId" minOccurs="0"/>
 *         &lt;element name="contextType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="guideSheetHistories" type="{}guideSheetHistories" minOccurs="0"/>
 *         &lt;element name="guideSheetItemKeys" type="{}keys" minOccurs="0"/>
 *         &lt;element name="guideSheetKeys" type="{}keys" minOccurs="0"/>
 *         &lt;element name="system" type="{}system" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getGuideSheetHistories", propOrder = {
    "capID",
    "contextType",
    "guideSheetHistories",
    "guideSheetItemKeys",
    "guideSheetKeys",
    "system"
})
public class GetGuideSheetHistories {

    protected CapId capID;
    protected String contextType;
    protected GuideSheetHistories guideSheetHistories;
    protected Keys guideSheetItemKeys;
    protected Keys guideSheetKeys;
    protected System system;

    /**
     * Gets the value of the capID property.
     * 
     * @return
     *     possible object is
     *     {@link CapId }
     *     
     */
    public CapId getCapID() {
        return capID;
    }

    /**
     * Sets the value of the capID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapId }
     *     
     */
    public void setCapID(CapId value) {
        this.capID = value;
    }

    /**
     * Gets the value of the contextType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextType() {
        return contextType;
    }

    /**
     * Sets the value of the contextType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextType(String value) {
        this.contextType = value;
    }

    /**
     * Gets the value of the guideSheetHistories property.
     * 
     * @return
     *     possible object is
     *     {@link GuideSheetHistories }
     *     
     */
    public GuideSheetHistories getGuideSheetHistories() {
        return guideSheetHistories;
    }

    /**
     * Sets the value of the guideSheetHistories property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuideSheetHistories }
     *     
     */
    public void setGuideSheetHistories(GuideSheetHistories value) {
        this.guideSheetHistories = value;
    }

    /**
     * Gets the value of the guideSheetItemKeys property.
     * 
     * @return
     *     possible object is
     *     {@link Keys }
     *     
     */
    public Keys getGuideSheetItemKeys() {
        return guideSheetItemKeys;
    }

    /**
     * Sets the value of the guideSheetItemKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keys }
     *     
     */
    public void setGuideSheetItemKeys(Keys value) {
        this.guideSheetItemKeys = value;
    }

    /**
     * Gets the value of the guideSheetKeys property.
     * 
     * @return
     *     possible object is
     *     {@link Keys }
     *     
     */
    public Keys getGuideSheetKeys() {
        return guideSheetKeys;
    }

    /**
     * Sets the value of the guideSheetKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keys }
     *     
     */
    public void setGuideSheetKeys(Keys value) {
        this.guideSheetKeys = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

}
