//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getGISLayersResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getGISLayersResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contextType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GISLayers" type="{}gisLayers" minOccurs="0"/>
 *         &lt;element name="mapServiceId" type="{}mapServiceId" minOccurs="0"/>
 *         &lt;element name="system" type="{}system" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getGISLayersResponse", propOrder = {
    "contextType",
    "gisLayers",
    "mapServiceId",
    "system"
})
public class GetGISLayersResponse {

    protected String contextType;
    @XmlElement(name = "GISLayers")
    protected GisLayers gisLayers;
    protected MapServiceId mapServiceId;
    protected System system;

    /**
     * Gets the value of the contextType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextType() {
        return contextType;
    }

    /**
     * Sets the value of the contextType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextType(String value) {
        this.contextType = value;
    }

    /**
     * Gets the value of the gisLayers property.
     * 
     * @return
     *     possible object is
     *     {@link GisLayers }
     *     
     */
    public GisLayers getGISLayers() {
        return gisLayers;
    }

    /**
     * Sets the value of the gisLayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link GisLayers }
     *     
     */
    public void setGISLayers(GisLayers value) {
        this.gisLayers = value;
    }

    /**
     * Gets the value of the mapServiceId property.
     * 
     * @return
     *     possible object is
     *     {@link MapServiceId }
     *     
     */
    public MapServiceId getMapServiceId() {
        return mapServiceId;
    }

    /**
     * Sets the value of the mapServiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapServiceId }
     *     
     */
    public void setMapServiceId(MapServiceId value) {
        this.mapServiceId = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

}
