//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 06:33:27 PM CST 
//


package com.accela.adapter.model.function;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inspectionGrade complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inspectionGrade">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifierDisplay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="keys" type="{}keys" minOccurs="0"/>
 *         &lt;element name="lowerMajorViolation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lowerScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="upperMajorViolation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="upperScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inspectionGrade", propOrder = {
    "identifierDisplay",
    "keys",
    "lowerMajorViolation",
    "lowerScore",
    "upperMajorViolation",
    "upperScore"
})
public class InspectionGrade {

    protected String identifierDisplay;
    protected Keys keys;
    protected String lowerMajorViolation;
    protected String lowerScore;
    protected String upperMajorViolation;
    protected String upperScore;

    /**
     * Gets the value of the identifierDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifierDisplay() {
        return identifierDisplay;
    }

    /**
     * Sets the value of the identifierDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifierDisplay(String value) {
        this.identifierDisplay = value;
    }

    /**
     * Gets the value of the keys property.
     * 
     * @return
     *     possible object is
     *     {@link Keys }
     *     
     */
    public Keys getKeys() {
        return keys;
    }

    /**
     * Sets the value of the keys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keys }
     *     
     */
    public void setKeys(Keys value) {
        this.keys = value;
    }

    /**
     * Gets the value of the lowerMajorViolation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowerMajorViolation() {
        return lowerMajorViolation;
    }

    /**
     * Sets the value of the lowerMajorViolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowerMajorViolation(String value) {
        this.lowerMajorViolation = value;
    }

    /**
     * Gets the value of the lowerScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowerScore() {
        return lowerScore;
    }

    /**
     * Sets the value of the lowerScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowerScore(String value) {
        this.lowerScore = value;
    }

    /**
     * Gets the value of the upperMajorViolation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpperMajorViolation() {
        return upperMajorViolation;
    }

    /**
     * Sets the value of the upperMajorViolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpperMajorViolation(String value) {
        this.upperMajorViolation = value;
    }

    /**
     * Gets the value of the upperScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpperScore() {
        return upperScore;
    }

    /**
     * Sets the value of the upperScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpperScore(String value) {
        this.upperScore = value;
    }

}
