//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.21 at 02:38:20 PM GMT+08:00 
//


package com.accela.cers.cap.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CERSGeographicPointLocationDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CERSGeographicPointLocationDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LatitudeMeasure">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="4"/>
 *               &lt;maxLength value="13"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LongitudeMeasure">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="4"/>
 *               &lt;maxLength value="13"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HorizontalAccuracyMeasure" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="HorizontalCollectionMethod">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;enumeration value="101"/>
 *               &lt;enumeration value="103"/>
 *               &lt;enumeration value="104"/>
 *               &lt;enumeration value="107"/>
 *               &lt;enumeration value="108"/>
 *               &lt;enumeration value="109"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GeographicReferencePoint">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;enumeration value="101"/>
 *               &lt;enumeration value="102"/>
 *               &lt;enumeration value="103"/>
 *               &lt;enumeration value="108"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HorizontalReferenceDatum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NAD27"/>
 *               &lt;enumeration value="NAD83"/>
 *               &lt;enumeration value="WGS84"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DataCollectionDate">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CERSGeographicPointLocationDataType", propOrder = {
    "latitudeMeasure",
    "longitudeMeasure",
    "horizontalAccuracyMeasure",
    "horizontalCollectionMethod",
    "geographicReferencePoint",
    "horizontalReferenceDatum",
    "dataCollectionDate"
})
public class CERSGeographicPointLocationDataType {

    @XmlElement(name = "LatitudeMeasure", required = true)
    protected String latitudeMeasure;
    @XmlElement(name = "LongitudeMeasure", required = true)
    protected String longitudeMeasure;
    @XmlElement(name = "HorizontalAccuracyMeasure", required = true)
    protected BigDecimal horizontalAccuracyMeasure;
    @XmlElement(name = "HorizontalCollectionMethod", required = true)
    protected BigInteger horizontalCollectionMethod;
    @XmlElement(name = "GeographicReferencePoint", required = true)
    protected BigInteger geographicReferencePoint;
    @XmlElement(name = "HorizontalReferenceDatum", required = true)
    protected String horizontalReferenceDatum;
    @XmlElement(name = "DataCollectionDate", required = true)
    protected XMLGregorianCalendar dataCollectionDate;

    /**
     * Gets the value of the latitudeMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitudeMeasure() {
        return latitudeMeasure;
    }

    /**
     * Sets the value of the latitudeMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitudeMeasure(String value) {
        this.latitudeMeasure = value;
    }

    /**
     * Gets the value of the longitudeMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitudeMeasure() {
        return longitudeMeasure;
    }

    /**
     * Sets the value of the longitudeMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitudeMeasure(String value) {
        this.longitudeMeasure = value;
    }

    /**
     * Gets the value of the horizontalAccuracyMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHorizontalAccuracyMeasure() {
        return horizontalAccuracyMeasure;
    }

    /**
     * Sets the value of the horizontalAccuracyMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHorizontalAccuracyMeasure(BigDecimal value) {
        this.horizontalAccuracyMeasure = value;
    }

    /**
     * Gets the value of the horizontalCollectionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHorizontalCollectionMethod() {
        return horizontalCollectionMethod;
    }

    /**
     * Sets the value of the horizontalCollectionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHorizontalCollectionMethod(BigInteger value) {
        this.horizontalCollectionMethod = value;
    }

    /**
     * Gets the value of the geographicReferencePoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGeographicReferencePoint() {
        return geographicReferencePoint;
    }

    /**
     * Sets the value of the geographicReferencePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGeographicReferencePoint(BigInteger value) {
        this.geographicReferencePoint = value;
    }

    /**
     * Gets the value of the horizontalReferenceDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalReferenceDatum() {
        return horizontalReferenceDatum;
    }

    /**
     * Sets the value of the horizontalReferenceDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalReferenceDatum(String value) {
        this.horizontalReferenceDatum = value;
    }

    /**
     * Gets the value of the dataCollectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataCollectionDate() {
        return dataCollectionDate;
    }

    /**
     * Sets the value of the dataCollectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataCollectionDate(XMLGregorianCalendar value) {
        this.dataCollectionDate = value;
    }

}
