//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.21 at 02:38:20 PM GMT+08:00 
//


package com.accela.cers.cap.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HWUnitPBRNotificationOfPropertyOwnersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HWUnitPBRNotificationOfPropertyOwnersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HWPBRNotificationOfPropertyOwner" type="{http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilitySubmittalQuery/1/05/}HWUnitPBRNotificationOfPropertyOwnerType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HWUnitPBRNotificationOfPropertyOwnersType", propOrder = {
    "hwpbrNotificationOfPropertyOwner"
})
public class HWUnitPBRNotificationOfPropertyOwnersType {

    @XmlElement(name = "HWPBRNotificationOfPropertyOwner", required = true)
    protected List<HWUnitPBRNotificationOfPropertyOwnerType> hwpbrNotificationOfPropertyOwner;

    /**
     * Gets the value of the hwpbrNotificationOfPropertyOwner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hwpbrNotificationOfPropertyOwner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHWPBRNotificationOfPropertyOwner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HWUnitPBRNotificationOfPropertyOwnerType }
     * 
     * 
     */
    public List<HWUnitPBRNotificationOfPropertyOwnerType> getHWPBRNotificationOfPropertyOwner() {
        if (hwpbrNotificationOfPropertyOwner == null) {
            hwpbrNotificationOfPropertyOwner = new ArrayList<HWUnitPBRNotificationOfPropertyOwnerType>();
        }
        return this.hwpbrNotificationOfPropertyOwner;
    }

}
