//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.21 at 02:38:20 PM GMT+08:00 
//


package com.accela.cers.cap.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSetDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TransactionKey">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilitySubmittalQuery/1/05/}GUID">
 *               &lt;minLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TransactionStatus">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilitySubmittalQuery/1/05/>TransactionStatusType">
 *                 &lt;attribute name="queuePosition" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FacilitySubmittal" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilitySubmittalQuery/1/05/}FacilitySubmittalType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataSetDateTime",
    "transactionKey",
    "transactionStatus",
    "facilitySubmittal"
})
@XmlRootElement(name = "RegulatorFacilitySubmittals")
public class RegulatorFacilitySubmittals {

    @XmlElement(name = "DataSetDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataSetDateTime;
    @XmlElement(name = "TransactionKey", required = true)
    protected String transactionKey;
    @XmlElement(name = "TransactionStatus", required = true)
    protected RegulatorFacilitySubmittals.TransactionStatus transactionStatus;
    @XmlElement(name = "FacilitySubmittal")
    protected List<RegulatorFacilitySubmittals.FacilitySubmittal> facilitySubmittal;

    /**
     * Gets the value of the dataSetDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataSetDateTime() {
        return dataSetDateTime;
    }

    /**
     * Sets the value of the dataSetDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataSetDateTime(XMLGregorianCalendar value) {
        this.dataSetDateTime = value;
    }

    /**
     * Gets the value of the transactionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionKey() {
        return transactionKey;
    }

    /**
     * Sets the value of the transactionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionKey(String value) {
        this.transactionKey = value;
    }

    /**
     * Gets the value of the transactionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RegulatorFacilitySubmittals.TransactionStatus }
     *     
     */
    public RegulatorFacilitySubmittals.TransactionStatus getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * Sets the value of the transactionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegulatorFacilitySubmittals.TransactionStatus }
     *     
     */
    public void setTransactionStatus(RegulatorFacilitySubmittals.TransactionStatus value) {
        this.transactionStatus = value;
    }

    /**
     * Gets the value of the facilitySubmittal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facilitySubmittal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacilitySubmittal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegulatorFacilitySubmittals.FacilitySubmittal }
     * 
     * 
     */
    public List<RegulatorFacilitySubmittals.FacilitySubmittal> getFacilitySubmittal() {
        if (facilitySubmittal == null) {
            facilitySubmittal = new ArrayList<RegulatorFacilitySubmittals.FacilitySubmittal>();
        }
        return this.facilitySubmittal;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilitySubmittalQuery/1/05/}FacilitySubmittalType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FacilitySubmittal
        extends FacilitySubmittalType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilitySubmittalQuery/1/05/>TransactionStatusType">
     *       &lt;attribute name="queuePosition" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TransactionStatus {

        @XmlValue
        protected TransactionStatusType value;
        @XmlAttribute(name = "queuePosition")
        protected Integer queuePosition;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link TransactionStatusType }
         *     
         */
        public TransactionStatusType getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransactionStatusType }
         *     
         */
        public void setValue(TransactionStatusType value) {
            this.value = value;
        }

        /**
         * Gets the value of the queuePosition property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getQueuePosition() {
            return queuePosition;
        }

        /**
         * Sets the value of the queuePosition property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setQueuePosition(Integer value) {
            this.queuePosition = value;
        }

    }

}
