//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.27 at 09:00:25 PM CST 
//


package com.accela.cers.inspection.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CMEDataStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CMEDataStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Approved"/>
 *     &lt;enumeration value="Deleted"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CMEDataStatusType")
@XmlEnum
public enum CMEDataStatusType {


    /**
     * Approved is valid for EDT submissions.
     * 
     */
    @XmlEnumValue("Approved")
    APPROVED("Approved"),

    /**
     * Deleted is valid for EDT submissions.
     * 
     */
    @XmlEnumValue("Deleted")
    DELETED("Deleted");
    private final String value;

    CMEDataStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CMEDataStatusType fromValue(String v) {
        for (CMEDataStatusType c: CMEDataStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
