//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 09:18:34 AM CST 
//


package com.accela.cers.inspection.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnforcementViolationsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnforcementViolationsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EnforcementViolation" type="{http://cersservices.calepa.ca.gov/Schemas/RegulatorCMESubmit/1/04/}EnforcementViolationType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnforcementViolationsType", propOrder = {
    "enforcementViolation"
})
public class EnforcementViolationsType {

    @XmlElement(name = "EnforcementViolation", required = true)
    protected List<EnforcementViolationType> enforcementViolation;

    /**
     * Gets the value of the enforcementViolation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enforcementViolation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnforcementViolation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnforcementViolationType }
     * 
     * 
     */
    public List<EnforcementViolationType> getEnforcementViolation() {
        if (enforcementViolation == null) {
            enforcementViolation = new ArrayList<EnforcementViolationType>();
        }
        return this.enforcementViolation;
    }

}
